### ISSUE TITLE
Support for Gemsets

### ISSUE THREAD

**Issue by Mic92** [terlar/fry#11]
It would be cool, if gemsets and `.ruby-gemset` would be supported at some point.

**Comment by robsonpeixoto** [comment]
But sometimes you wanna use gemset to separate gems for different **not ruby** projects projects. Sometimes you just use to compile css or other tool like that. But different projects can use different versions of the same tool to the same ruby version.

**Comment by terlar** [comment]
Fair point, any idea how this would work? I haven't really looked into the gemset stuff.

**Comment by robsonpeixoto** [comment]
I'm not a ruby developer. I just use tools write in ruby. Sorry =/

**Comment by robsonpeixoto** [comment]
https://github.com/jf/rbenv-gemset/search?utf8=%E2%9C%93&q=export
Probable just need to create these  env variables:
- RBENV_GEMSET_SYSTEM_ROOT
- GEM_HOME
- GEM_PATH

But need to read the code
