### ISSUE TITLE
fry config installer does not set the installer

### ISSUE THREAD

**Issue by jordelver** [terlar/fry#38]
I've been trying to set the fry installer to ruby-build, but it does not seem to work.

```
fry config installer ruby-build
```

```
fry config
usage: fry config <name> [<value>]

Available configuration:

    auto [on|off|1|0]         switch ruby on directory change
    prepend [on|off|1|0]      prepend ruby path when used
    path, rubies [<path>]     path where fry looks for rubies
    installer [<installer>]   switch ruby installer to use

Current configuration:
    Auto-Switch: off
    Prepend Path: off
    Path: /Users/jord/.rubies
    Installer:
```

Am I doing something wrong? Quite possible as I've just started using both fry and fish.

**Comment by terlar** [comment]
Do you have `ruby-build` installed?

**Comment by terlar** [comment]
I am creating a Dockerfile for the repository to be able to debug this more throughly. It should be the correct way to do it. But won't work without the binary available in path.

**Comment by jordelver** [comment]
Yes.

```
$ type ruby-build
ruby-build is /usr/local/bin/ruby-build
$ which ruby-build
/usr/local/bin/ruby-build
```

Mine is installed in `/usr/local`. It's also in my `PATH`.

```
$ echo $PATH
/Users/jord/bin:/usr/local/share/npm/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by terlar** [comment]
Looks alright, should work. Could you provide the output from these to help me debugging?

```
set -U | grep fry
set -g | grep fry
set -l | grep fry
fish --version
```

**Comment by jordelver** [comment]
Sure, the top three don't return anything.

```
$ set -U | grep fry
/Users/jord exited 1

$ set -g | grep fry
/Users/jord exited 1

$ set -l | grep fry
/Users/jord exited 1

$ fish --version
fish, version 2.1.2
```

**Comment by jordelver** [comment]
Sorry, I've just realised that I was running under tmux. Without tmux I get this output.

```
$ set -U | grep fry
fry_auto_switch 0
fry_prepend_path 0
fry_rubies /Users/jord/.rubies

$ set -g | grep fry
fish_complete_path '/usr/local/Cellar/fry/HEAD/share/fry/completions'  '/Users/jord'…
fish_function_path '/usr/local/Cellar/fry/HEAD/share/fry/functions'  '/Users/jord/.'…
history 'set -U | grep fry'  'clear'  'c'  'fry config'  'fry config install ruby'…

$ set -l | grep fry

$ fish --version
fish, version 2.1.2
```

**Comment by terlar** [comment]
I wonder if it is because of tmux or you tried to do the `fry configure installer ruby-build`.

You could always try to set it manually, `fry configure` is bascially just a wrapper around `set`.

Try to do: `set -U fry_installer ruby-build`

If that doesn't work something is seriously wrong.

**Comment by terlar** [comment]
I think I have a fix for this:

https://github.com/terlar/fry/pull/40

**Comment by terlar** [comment]
It should be working now, otherwise reopen.

**Comment by jordelver** [comment]
Sorry for the late response. I had trouble updating to the latest version using Homebrew. This is now working. Thank you :+1:
