### ISSUE TITLE
Ruby path first after switching.

### ISSUE THREAD

**Issue by fazibear** [terlar/fry#41]
Is there a way to fry won't add ruby path at the beginning ?
Right after `fry use ...` I have to `set PATH ./bin $PATH` to make spring works.

Cheers.

**Comment by terlar** [comment]
It is not adding the ruby path the the beginning. The default behaviour is to add it last to `fish_user_paths`.

This can be toggled through:

```
fry config prepend on
```

If you want to have `./bin` before, you should just add that to `fish_user_paths`. This is the way to manipulate the PATH variable in fish with custom entries.

This list is maintained separetely and will be prepended to PATH.

**Comment by fazibear** [comment]
Thanks for reply. It works, but cause some warnings :
```
set: Warning: path component ./node_modules/.bin may not be valid in PATH.
set: No such file or directory
set: Warning: path component ./bin may not be valid in PATH.
set: No such file or directory
```

How can I avoid this ?

**Comment by fazibear** [comment]
Never mind just add -U switch. Thanks once again :)
